### ISSUE TITLE
Clarify name of offset lookup methods

### ISSUE THREAD

**Issue by cdlm** [SquareBracketAssociates/Booklet-AReflectiveKernel#5]
The naming of `offsetFromObjectOfInstanceVariable:` and `offsetFromClassOfInstanceVariable:` are confusing. Suggestions:
- `offsetOfInstanceVariableFromObject:` (but that suggests the argument is an object not an instvar name
- `instanceVariableOffsetFromObject:` (same)
- `fromObjectOffsetOfInstanceVariable:`

**Comment by Ducasse** [comment]
I will check this for the final version

**Comment by Ducasse** [comment]
I shorten the names

- offsetFromClassOfInstanceVariable: -> ivClassOffset:
- offsetFromObjectOfInstanceVariable: -> ivOffset:
