### ISSUE TITLE
Mention class accessor primitives in the book

### ISSUE THREAD

**Issue by cdlm** [SquareBracketAssociates/Booklet-AReflectiveKernel#7]
…or provide them in the skeleton.

Idea: provide the accessor, but leave the offset accessor to do; it would hopefully make students think about why they can put a fixed number there…

**Comment by Ducasse** [comment]
Yes I added a mention to the accessor primitives and I like your ideas to put them in the skeleton.

**Comment by Ducasse** [comment]
Done
